openapi: 3.1.0
info:
  title: SecureLens Vulnerability Ingestion API
  version: 1.0.0
  description: |
    Versioned ingestion contract for vulnerability snapshots submitted by external scanners.
servers:
  - url: /api/v1
paths:
  /ingestion/vulnerabilities:
    post:
      summary: Ingest vulnerability snapshot
      operationId: ingestVulnerabilitySnapshot
      security:
        - BearerToken: []
      tags:
        - Ingestion
      parameters:
        - in: header
          name: Idempotency-Key
          required: true
          schema:
            type: string
            format: uuid
          description: Client-generated unique snapshot key used for idempotency.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VulnerabilitySnapshotRequest'
      responses:
        '202':
          description: Snapshot accepted for asynchronous processing.
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                  - snapshot_id
                properties:
                  status:
                    type: string
                    enum: [accepted]
                  snapshot_id:
                    type: string
                    format: uuid
        '401':
          description: Missing or invalid authentication token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Validation error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '429':
          description: Rate limit exceeded.
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
      bearerFormat: Token
  headers:
    X-RateLimit-Limit:
      description: Request quota per rate-limit window.
      schema:
        type: integer
    X-RateLimit-Remaining:
      description: Remaining requests in current rate-limit window.
      schema:
        type: integer
    X-RateLimit-Reset:
      description: UNIX timestamp when the current window resets.
      schema:
        type: integer
  schemas:
    VulnerabilitySnapshotRequest:
      type: object
      required:
        - project_slug
        - snapshot_id
        - source
        - ingested_at
        - vulnerabilities
      properties:
        project_slug:
          type: string
          maxLength: 255
          description: Target project slug.
        snapshot_id:
          type: string
          format: uuid
          description: Unique snapshot identifier.
        source:
          type: string
          enum: [osv, ghsa]
        ingested_at:
          type: string
          format: date-time
        vulnerabilities:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/VulnerabilityInput'
    VulnerabilityInput:
      type: object
      required:
        - osv_url
        - ecosystem
        - package_name
        - version
      properties:
        osv_url:
          type: string
          format: uri
          maxLength: 500
        cvss_score:
          type: number
          minimum: 0
          maximum: 10
          nullable: true
        ecosystem:
          type: string
          maxLength: 100
        package_name:
          type: string
          maxLength: 255
        version:
          type: string
          maxLength: 255
        fixed_version:
          type: string
          maxLength: 255
          nullable: true
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    ValidationErrorResponse:
      type: object
      required:
        - message
        - errors
      properties:
        message:
          type: string
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
